/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6_3cc52365210e4a818a20d77cb00ec9f3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6_3cc52365210e4a818a20d77cb00ec9f3/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6_3cc52365210e4a818a20d77cb00ec9f3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6_3cc52365210e4a818a20d77cb00ec9f3/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.26.10_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6_3cc52365210e4a818a20d77cb00ec9f3/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
