/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MyAlert: typeof import('./src/components/MyAlert.vue')['default']
    MyCard: typeof import('./src/components/sidepanel/cards/MyCard.vue')['default']
    MyInput: typeof import('./src/components/MyInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidepanel: typeof import('./src/components/sidepanel/index.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.1_@babel+parser@7.27.0_embla-carousel@8.5.2_magicast@0.3.5_typescript@5.6._e797bd20670649643f36f6fade6b6816/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
